version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres-refreshment
    ports:
      - '5432:5432'
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis-refreshment
    ports:
      - '6379:6379'
    volumes:
      - redis_vol:/data

volumes:
  postgres_vol:
  redis_vol:
